### ISSUE TITLE
Resetting a session

### ISSUE THREAD

**Issue by jcltravels** [lealvona/MemberBarry#6]
Can you guide me on how to reset a particular session?
I don't want to delete everything just specific session.

**Comment by lealvona** [comment]
Do you want to delete the session from the backend sqlite db; from the chromadb; or are do you want to reset the current working context while in a chat? If you can explain in greater detail what your use case is, I may be able to help.

Be advised, this project is in flux; I'm in the process of reworking some of the backend session management, and adding document-based RAG. This will cause some changes to how sessions are handled. 

Also some relevant methods, such as `delete_embedding()` are not yet implemented in the master branch. They will be implemented in due time.

**Comment by jcltravels** [comment]
Thanks for the reply.  I am using the same "session_id" and I was trying to reset my session in the chroma_client.
If I understood correctly -- I would need to do that in order to "reset" the memory?

**Comment by lealvona** [comment]
The concept of a "reset" is still a little nebulous. Do you want to delete items from the chromadb collection that all have the same session_id? This would effectively "reset" the session in the context of chromadb. There are the correlated SQLite entries, of course. 

Short answer, to extend your own fork to clear entries in chromadb, you'll need to find a place to implement a call to `self.collection.delete(where={'session_id': session_id})`

---

However, If you wanted to scrub all the datastores of all the instances of data correlated to a given session_id, you'll need the following methods:

```python
def delete_all_session_embeddings(self, session_id=None):
    """
    Delete all embeddings for a given session_id.

    Parameters:
    session_id (str): The session ID associated with the embeddings to be deleted.
    """
    if not session_id:
        session_id = self.session_id

    self.collection.delete(where={'session_id': session_id})

def delete_all_conversations(self, session_id=None):
    """Delete all conversations for a given session_id."""
    if not session_id:
        session_id = self.session_id

    c = self.conn.cursor()
    c.execute(
        """DELETE FROM conversations
        WHERE session_id=?""",
        (session_id,))
    self.conn.commit()

def delete_all_summaries(self, session_id=None):
    """Delete all summaries for a given session_id."""
    if not session_id:
        session_id = self.session_id

    c = self.conn.cursor()
    c.execute(
        """DELETE FROM summaries
        WHERE session_id=?""",
        (session_id,))
    self.conn.commit()
```

Furthermore, in the coming version, the document store is working, so there is another `filenames` table to contend with as well.

Again this project is in flux, so I would encourage you to wait before you request features, and investigate other branches of the project to see if any of your questions or needs are in development.
