### ISSUE TITLE
Using GPT-4o 

### ISSUE THREAD

**Issue by jcltravels** [lealvona/MemberBarry#7]
Is using the new model as simple has changing out the name in the “env” variable?

thanks for your help and patience.

**Comment by lealvona** [comment]
@jcltravels Yes, setting the `OPENAI_MODEL` "env" variable [here](https://github.com/lealvona/MemberBarry/blob/e0caf0e30e4084ef96a2554c557f84c5e36ce958/.env.shadow#L7) to "gpt-4o" as specified [here](https://platform.openai.com/docs/models/gpt-4o) will use the GPT-4o model, provided the account associated with the `OPENAI_API_KEY` and `OPENAI_ORG_ID` has access to the updated model.
